"""initial

Revision ID: e4839e10aedc
Revises: 
Create Date: 2026-05-03 10:07:41.601085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4839e10aedc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('profile', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    # ### end Alembic commands ###
