"""add recipe fields

Revision ID: e8373ba0fcf1
Revises: 316a7204bde0
Create Date: 2026-05-14 16:21:04.182588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8373ba0fcf1'
down_revision = '316a7204bde0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prep_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('prep_time')

    # ### end Alembic commands ###
